const String privaryIntroduction =
    "Welcome to GameZone. We value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our App. By accessing or using the App, you consent to the practices described in this Privacy Policy.";
const String collectedInformation =
    "\n1.1 Personal Information\n\nWe may collect certain personally identifiable information (\"Personal Information\") from you when you use the App. This may include but is not limited to:\nName\nEmail address\nPhone number\nUser credentials (username and password)\nPayment and billing information\nProfile picture (if you choose to upload one)\nDevice information (e.g., device model, operating system version, IP address, mobile network information)\n\n1.2 Non-Personal Information.\n\nIn addition to Personal Information, we may also collect non-personal information such as usage data, device type, and interactions with the App. This information helps us improve our services and user experience.\n\n1.3 Cookies and Similar Technologies.\n\nWe may use cookies and similar tracking technologies to enhance your experience with the App. Cookies are small data files stored on your device that help us recognize you and understand how you interact with the App";

const String usedInformation =
    "\n\nHow We Use Your Information\n\nWe use the information we collect for various purposes, including but not limited to:\nProviding and improving the App's features and functionality.\nPersonalizing your experience with the App.\nResponding to your inquiries, comments, or feedback.\nSending you updates, promotions, and other communications related to the App (you can opt-out at any time).\nProcessing transactions and payments.\nConducting data analysis and research to improve our services.";

const String restData =
    "\n\nHow We Share Your Information\n\nWe will not share your Personal Information with third parties except in the following circumstances:\nWith your consent: We may share your information with third parties if you give us explicit consent to do so.\n\nService Providers: We may share your information with trusted third-party service providers who assist us in delivering and maintaining the App. These service providers are obligated to keep your information confidential and use it only for specific purposes related to the App.\n\nLegal Requirements: We may disclose your information if required by law or in response to valid legal requests, such as court orders or government investigations.\n\nBusiness Transfers: In the event of a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred as part of the transaction.\n\nData Security\nWe implement appropriate security measures to protect your information from unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet or electronic storage is entirely secure, and we cannot guarantee absolute security.\n\nYour Choices\n\nYou have the right to access, update, or delete your Personal Information. You can also choose to opt-out of receiving promotional communications from us. If you wish to exercise any of these rights, please contact us at 27imranshaikh05@gmail.com.Children's Privacy\nThe App is not intended for use by individuals under the age of [13/16/18, depending on the jurisdiction]. We do not knowingly collect Personal Information from children without parental consent. If you believe we have inadvertently collected information from a child, please contact us, and we will promptly delete it.Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. We will notify you of any significant changes by posting the updated policy on our website or through the App.Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or our data practices, please contact us at [your contact email].Conclusion\nThank you for trusting GameZone. We are committed to protecting your privacy and will continue to improve our data protection practices to ensure the security of your information. By using the App, you agree to this Privacy Policy and our Terms of Service.";
